### ISSUE TITLE
theres is no your drl algorithm, and I don`t understand.

### ISSUE THREAD

**Issue by xuyinbo** [pulver22/QLAB#3]
I am a beginner in DRL, and I appreciate your work very much! I found there is no your reinforcement algorithm, is that right? So I cannot understand how your code works. Can you include you reinforcement learning algorithm in you code? I want to learn more about it, plz.

**Comment by pulver22** [comment]
Hi @xuyinbo,
thank you for appreciating my work. 
The algorithm is not released at the moment, I am waiting the corresponding paper is accepted.

However, QLAB is intended to only be a simulator to benchmark different DRL algorithms applied to autonomous landing for UAV using the ROS services I implemented. Therefore the current idea is that you develop and implement your own algorithm and the you test it within QLAB.

My algorithm, if you didn't read the paper available on arxiv, is a modification of the famous DQN. If you want to develop your own solution you can start from there.

Otherwise I will release the code as soon as the publication is accepted.

I hope to have solved your doubts!

**Comment by xuyinbo** [comment]
@pulver22 Thanks for your reply! I have read your paper on arXiv, a good job.
